"use client";
import {useEffect,useMemo,useState} from "react";
import ManagerShell from "../ManagerShell";
type Order={property?:{id:string;title:string;location?:string|null;imageUrl?:string|null};amount:number;status:string};
export default function ManagerPropertiesPage(){
 const [orders,setOrders]=useState<Order[]>([]); const [name,setName]=useState("Manager");
 useEffect(()=>{Promise.all([fetch("/api/manager/orders",{cache:"no-store"}),fetch("/api/manager/overview",{cache:"no-store"})]).then(async([a,b])=>{if(a.status===401){location.href="/manager-login";return} const aj=await a.json(),bj=await b.json();setOrders(aj.orders||[]);setName(bj?.manager?.name||"Manager")})},[]);
 const props=useMemo(()=>{const m=new Map<string,any>();orders.forEach(o=>{if(o.property&&!m.has(o.property.id))m.set(o.property.id,o.property)});return [...m.values()]},[orders]);
 return <ManagerShell managerName={name}><div className="mx-head"><span>PROPERTY OPERATIONS</span><h1>Properties</h1><p>Review the property catalog represented in your manager order flow.</p></div><div className="mx-note"><strong>Manager-scoped visibility</strong><p>Property access is enforced by the platform APIs. This workspace shows properties attached to your manager's orders; property creation and global catalog controls remain outside this manager view.</p></div><section className="mx-grid">{props.map(p=><article key={p.id} className="mx-card"><div className="mx-img">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<b>Housing.pro</b>}</div><div><small>{p.location||"Marketplace Property"}</small><h2>{p.title}</h2><span>Visible through your assigned order flow</span></div></article>)}{!props.length&&<div className="mx-empty">No property records are attached to your current orders yet.</div>}</section><style jsx global>{`.mx-head span{font-size:11px;font-weight:800;letter-spacing:.12em;color:#64748b}.mx-head h1{margin:5px 0;font-size:30px}.mx-head p{margin:0 0 20px;color:#64748b;font-size:13px}.mx-note{background:#0f172a;color:#fff;border-radius:15px;padding:18px 20px;margin-bottom:18px}.mx-note strong{font-size:14px}.mx-note p{margin:7px 0 0;color:#cbd5e1;font-size:12px;line-height:1.6}.mx-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.mx-card{background:#fff;border:1px solid #e5e7eb;border-radius:15px;overflow:hidden}.mx-img{height:150px;background:#f1f5f9;display:grid;place-items:center;color:#94a3b8}.mx-img img{width:100%;height:100%;object-fit:cover}.mx-card>div:last-child{padding:15px}.mx-card small{color:#64748b;font-size:10px}.mx-card h2{font-size:16px;margin:5px 0}.mx-card span{font-size:10px;color:#64748b}.mx-empty{grid-column:1/-1;background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:50px;text-align:center;color:#64748b}@media(max-width:850px){.mx-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.mx-grid{grid-template-columns:1fr}}`}</style></ManagerShell>
}

